### ISSUE TITLE
Change clipboard icon to button with text

### ISSUE THREAD

**Issue by mochaul** [RistekCSUI/susunjadwal#12]
In "Daftar Jadwal" change copy link icon and make it more apparent by changing it to a button that says "Bagikan Jadwal Ini".

**Comment by albadrun** [comment]
How about this image? https://image.flaticon.com/icons/svg/34/34735.svg

**Comment by satraul** [comment]
> How about this image? https://image.flaticon.com/icons/svg/34/34735.svg

The issues argues that we should change the icon to a button with text. Not change the icon image.

**Comment by mochaul** [comment]
Yes, the reason being we need to emphasize on the positive action being "Share Jadwal" and the negative being "Delete Jadwal" (Trashcan icon). To do that we can make the "Share Jadwal" a button instead.

**Comment by satraul** [comment]
closing design issues
