### ISSUE TITLE
Add "Share" button for created schedule

### ISSUE THREAD

**Issue by mochaul** [RistekCSUI/susunjadwal#15]
Add a "Share" button in each "Jadwal" for sharing with others

**Comment by albadrun** [comment]
can you elaborate this? where to put the button, etc

**Comment by mochaul** [comment]
![image](https://user-images.githubusercontent.com/31040541/62143412-269f3380-b31a-11e9-9f17-ad4e3213abd3.png)

We can put it on the right side, the opposite of the name of the "Jadwal"

**Comment by mochaul** [comment]
![image](https://user-images.githubusercontent.com/31040541/62143412-269f3380-b31a-11e9-9f17-ad4e3213abd3.png)

We can put it on the right side, the opposite of the name of the "Jadwal"

**Comment by mochaul** [comment]
We can put it on the right side, on the opposite side of the "Jadwal" name

**Comment by satraul** [comment]
the core problem is some people don't know that the links can be shared

**Comment by satraul** [comment]
closing design issues
