### ISSUE TITLE
In each "Jadwal" add color coding per courses

### ISSUE THREAD

**Issue by mochaul** [RistekCSUI/susunjadwal#16]
In each "Jadwal" add color coding per courses to improve clarity.

**Use Case**

- As a student, when I have finished choosing 6 courses to take this semester, I will be able to see each of my courses in a schedule color-coded for each course.

Example:
1st chosen course (Red)
2nd chosen course (Green)
3rd chosen course (Blue)
4th chosen course (Yellow)
etc.
(The color is chosen by devs and cannot be changed)

This will enable students to easily distinguish courses when seeing the schedule.

![image](https://user-images.githubusercontent.com/31040541/62036410-f40f1100-b21b-11e9-8617-24efa19ca913.png)

**Comment by satraul** [comment]
Please clarify the use-case, this seems pretty complex (not just frontend)

**Comment by mochaul** [comment]
Done, hope it clear things up

**Comment by mochaul** [comment]
@fatanugraha @albadrun any comment on this?

**Comment by satraul** [comment]
closing design issues
