### ISSUE TITLE
Implement :nth-child(even) coloring

### ISSUE THREAD

**Issue by mochaul** [RistekCSUI/susunjadwal#17]
Add color differences for courses chosen in "Buat Jadwal" for better differentiation

![image](https://user-images.githubusercontent.com/31040541/62036728-8b746400-b21c-11e9-9f83-69f93386f117.png)

**Comment by albadrun** [comment]
@fatanugraha have explanation about this

**Comment by fatanugraha** [comment]
@mochaul can you provide us the color codes?

**Comment by mochaul** [comment]
@fatanugraha let me check our branding guideline first

**Comment by mochaul** [comment]
I have discussed this with our DPD SIG and have come up with this solution:

![image](https://user-images.githubusercontent.com/31040541/62285950-e73f2700-b480-11e9-85da-60a953d6e4c1.png)

The hex code is: 3C2E18

**Comment by satraul** [comment]
Resolved in #34
