### ISSUE TITLE
Fix http/https behind proxy

### ISSUE THREAD

**Issue by albadrun** [RistekCSUI/susunjadwal#26]
**This issue is a:** 

- [x] refactor request

**Current behavior:**
Flask redirect `url_for` with `http` scheme because of nginx proxy. Need to solve this in a better way. Now using `url_for_custom` as workaround to fix this problems. See the code [here](
https://github.com/RistekCSUI/susunjadwal/blob/master/backend/uploader/utils.py).

**Requested behavior:**
Any way better than existing.

**Why this behavior is better:**
No need to modify built in function.

**Comment by aselhid** [comment]
have you tried setting `X-Forwarded-Proto` header from nginx to your desired schema? Based on this [link](https://stackoverflow.com/a/45693122) flask can automatically set your schema based on that header

**Comment by satraul** [comment]
Has this been fixed? Please document how you solved this issue @albadrun
