### ISSUE TITLE
Make mobile view in Buat Jadwal more compact

### ISSUE THREAD

**Issue by satraul** [RistekCSUI/susunjadwal#3]
**Use Case**
- User opens Buat Jadwal page in mobile (let's say iPhone X)
- User sees >=8 available class entries

**Explanation**
Currently, the mobile view in Buat Jadwal can only show very few entires due to the size.

**Comment by albadrun** [comment]
Could you give some screenshot?

**Comment by satraul** [comment]
![image](https://user-images.githubusercontent.com/24841231/62109131-def6b880-b2d5-11e9-8a5e-bb392bc4b429.png)

After talking with the design team, the current design is deemed better. Closing the issue, the code is in `mobile/compact`
