### ISSUE TITLE
Change course schedule update mechanism

### ISSUE THREAD

**Issue by arielmiki** [RistekCSUI/susunjadwal#32]
**This issue is a:** 

- [ ] bug report
- [x] feature request
- [ ] styling change request

**Current behavior:**

I see that currently, course schedule is updated using flask cron cli command. I don't know if this is triggered manually or using a scheduler in the server (I don't know if it is correct because I am not familiar with flask cron).  At least, that is what I can conclude when seeing [this](https://github.com/RistekCSUI/susunjadwal/blob/master/backend/app/cron.py). However, recent course update from SIAK is not reflected by Susun Jadwal.

**Requested behavior:**

Maybe, we can use in-memory cache and give it TTL, so users always get the most updated schedule. Besides, I think we also need to make `update_courses` function is able to update the schedule for each major separately. BTW, I don't know if it is possible.

**Why this behavior is better:**

**Comment by satraul** [comment]
@albadrun Any comment?

**Comment by fairuzi10** [comment]
Currently, the scheduler is set once per hour, so maybe the schedule in SIAK is updated in the last hour. I think the cache solution is basically equivalent to the scheduler with TTL 1 hour. I believe the solution is to run the scheduler more frequently.

**Comment by fairuzi10** [comment]
Closing this as we update [the cron job readme](https://github.com/RistekCSUI/susunjadwal/pull/43/files). The frequency is subject to discussion of the active maintainers.
