### ISSUE TITLE
Navbar user still visible on 404 page, in condition user not login

### ISSUE THREAD

**Issue by muhsatrio** [RistekCSUI/susunjadwal#38]
**This issue is a:** 

- [x] bug report
- [ ] feature request
- [ ] styling change request

**Current behavior:**

This condition is happened when I am not login as the user (actually, I'm not UI student, so can't try to login with SSO user also),
If I go to click URL outside of available routes, like this picture below
![Screenshot from 2020-07-22 00-18-16](https://user-images.githubusercontent.com/11547086/88086348-6c02e380-cbb1-11ea-8699-e8b5fbf1a478.jpg)
It will show 404 not found page, but still there navbar for user menu who had login

**Requested behavior:**

Added authorization for navbar to show just if user has been login

**Why this behavior is better:**
To make sure the visitor outside user can not access available menu anymore

**Comment by muhsatrio** [comment]
@albadrun @mochaul @satraul @genturwt @fatanugraha @fairuzi10 @hilyafesmia

**Comment by satraul** [comment]
Fixed in #39 Thanks for the contribution! Clean solution

**Comment by muhsatrio** [comment]
You're welcome, thanks for accepting my PR! @satraul
