### ISSUE TITLE
Extract `backend/sso` into a seperate pip package

### ISSUE THREAD

**Issue by satraul** [RistekCSUI/susunjadwal#4]
**Explanation**
I'm pretty sure the SSO UI code we have in `backend/sso` can be extracted into a pip package ala the [PHP library](https://github.com/RistekCSUI/SSO) we already have.
Some changes are probably needed to make it more modular first, as it should be able to work with both Flask and Django.

**Comment by albadrun** [comment]
@fatanugraha working on it, probably after siak-war

**Comment by satraul** [comment]
Great job @fatanugraha https://github.com/RistekCSUI/django-sso-ui

Closing
