### ISSUE TITLE
Add a notification that sometimes courses schedule can change

### ISSUE THREAD

**Issue by mochaul** [RistekCSUI/susunjadwal#9]
Add a notification that sometimes courses schedule can change and students should always recheck their planned schedule.

**Comment by albadrun** [comment]
What kind of notification? Last updated or what?

**Comment by mochaul** [comment]
Add something like a red-colored text saying that the course may change on each schedule created

**Comment by satraul** [comment]
can be inserted to https://github.com/RistekCSUI/susunjadwal/issues/8
